---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: mso
  connection: local
  gather_facts: False
  vars_files:
    - vars/mso_variables.yml
  vars:
    mso_login: &mso_login
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False     
  
  tasks:
    - name: Create Tenant
      cisco.mso.mso_tenant:
        <<: *mso_login
        state: "present"
        tenant: "{{ tenant }}"
        description: "Tenant Created Using Ansible"

    - name: Create Schema & Template
      cisco.mso.mso_schema_template:
        <<: *mso_login
        state: "present"
        schema: "{{ schema }}"
        tenant: "{{ tenant }}"
        template: "{{ template }}"

    - name: Create VRF
      cisco.mso.mso_schema_template_vrf:
        <<: *mso_login
        state: "present"
        schema: "{{ schema }}"
        template: "{{ template }}"
        vrf: "{{ vrf }}"

    - name: Create Bridge Domain
      cisco.mso.mso_schema_template_bd:
        <<: *mso_login
        state: "present"
        validate_certs: False
        schema: "{{ schema }}"
        template: "{{ template }}"
        bd: "{{ bd }}"
        vrf:
          name: "{{ vrf }}"
          schema: "{{ schema }}"
          template: "{{ template }}"

    - name: Create Filter
      cisco.mso.mso_schema_template_filter_entry:
        <<: *mso_login
        state: "present"
        schema: "{{ schema }}"
        template: "{{ template }}"
        filter: "{{ filter }}"
        ethertype: "ipv4"
        ip_protocol: "tcp"
        destination_from: "unspecified"
        destination_to: "unspecified"
        source_from: "unspecified"
        source_to: "unspecified"
        entry: "{{ entry }}"
        arp_flag: "unspecified"

    - name: Create Contract
      cisco.mso.mso_schema_template_contract_filter:
        <<: *mso_login
        state: "present"
        schema: "{{ schema }}"
        template: "{{ template }}"
        filter: "{{ filter }}"
        filter_schema: "{{ filter_schema }}"
        filter_template: "{{ filter_template }}"
        filter_type: "{{ filter_type }}"
        contract: "{{ contract_name }}"
        contract_filter_type: "{{ contract_filter_type }}"
 

    - name: Create Application Profile
      cisco.mso.mso_schema_template_anp:
        <<: *mso_login
        state: "present"
        schema: "{{ schema }}"
        template: "{{ template }}"
        anp: "{{ anp }}"

    - name: Create EPG
      cisco.mso.mso_schema_template_anp_epg:
        <<: *mso_login
        state: "present"
        validate_certs: False
        schema: "{{ schema }}"
        template: "{{ template }}"
        anp: "{{ anp }}"
        epg: "{{ epg }}"
        bd:
          name: '{{ bd }}'
          schema: '{{ schema }}'
          template: '{{ template }}'

    - name: Associate contract to EPG
      cisco.mso.mso_schema_template_anp_epg_contract:
        <<: *mso_login
        state: "present"
        validate_certs: False
        schema: "{{ schema }}"
        template: "{{ template }}"
        anp: "{{ anp }}"
        epg: "{{ epg }}"
        contract:
          name: '{{ item.name }}'
          template: '{{ item.template }}'
          type: '{{ item.type }}'
      with_items: "{{ contracts }}"

    